name: smart-resume-builder-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - altair
      - flake8
      - IPython
      - numpy
      - openai
      - pandas
      - pyttsx3
      - python-dotenv
      - pytest
      - requests
      - scipy
      - spacy
      - speechrecognition
      - streamlit
      - streamlit-chat
      - streamlit-navigation-bar
      - torch
      - transformers
      - gitpython
      - jinja2
      - rich
      - tqdm
      - requests
      - pyarrow
      - pydantic
      - protobuf
      - streamlit-pdf-viewer
      - PyPDF2
      - sentence_transformers