name: smart-resume-builder-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - spacy==3.8.4
      - en-core-web-sm==3.8.0
      - pytest
      - flake8
      - streamlit==1.44.0
      - streamlit-chat==0.1.1
      - numpy
      - pandas
      - requests
      - pyarrow
      - pydantic
      - protobuf
      - gitpython
      - jinja2
      - rich
      - tqdm
