name: Run Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Python Version
        run: |
          which python
          python --version

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run Setup
        run: make setup
      
      - name: Run Linter
        run: make lint

      - name: Run Tests
        run: make test