name: Run Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true

      - name: Install Dependencies
        run: |
          conda env update --file environment.yml --name base
          pip install spacy pytest

      - name: Run Setup Script
        run: bash setup.sh

      - name: Run Linter
        run: make lint

      - name: Run Tests
        run: make test
