name: Run Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: smart-resume-builder-env  # Match 'name:' in your cleaned-up environment.yml
          auto-activate-base: false

      - name: Verify Environment
        run: |
          which python
          python --version
          pip list

      - name: Install SpaCy model
        run: python -m spacy download en_core_web_sm

      - name: Run Linter
        run: make lint

      - name: Run Tests
        run: make test
